server:
  port: 9002

# spring.cloud.stream.bindings.input [Consumer] -> MQ name
spring:
  cloud:
    stream:
      bindings:
        input: payments

# Spring string injection
com:
  angela:
    food:
      payment: http://localhost:9001